### ISSUE TITLE
Add panning to individual tracks

### ISSUE THREAD

**Issue by julianpoy** [julianpoy/HackTech2016#11]
Perhaps drag and drop or something of the sort

**Comment by torch2424** [comment]
Volume has already been done

And to be completely honest, I think panning should be pushed back. like I said panning wont be that apparent on laptop speakers, and I feel like it should be more of a priority of release candidate one

I feel like this should be closed, is that okay? How do you feel about that?

**Comment by julianpoy** [comment]
Sure. Can you create an issue for panning and throw it on the backburner or RC1? I don't want to forget about it, since it is a useful feature that wouldn't take _that_ much effort.

**Comment by torch2424** [comment]
Ill rename this one and re-assign it accordingly

**Comment by julianpoy** [comment]
This issue was moved to Kondeo/Flyxer#3
