### ISSUE TITLE
Be able to Remove Sounds

### ISSUE THREAD

**Issue by torch2424** [julianpoy/HackTech2016#24]
Currently they can be added and cannot be removed.

Perhaps We should also limit the number of tracks that can be added

**Comment by julianpoy** [comment]
As far as limiting the number of tracks that can be added: What if someone has their song in multiple pieces, or what if they have a long set to play? Perhaps we should place a limit on how many can play at a time?
Honestly, if the user plays too many and it gets laggy its their own damn fault. At that point they have 10+ tracks playing at the same time right? They should probably be looking for a higher price audio DAC anyway...

**Comment by torch2424** [comment]
True True, it would be their fault for adding 10+ tracks.

However, I think we should limit it to about 6 in that case. since we have #24 if a song is in pieces, they'll remove an old part and place in another or vice versa

Is this at all difficult to do? If it is, I'd understand, but if not, I say it wouldnt hurt. Though, I do feel like this should be implemented, but the priority is possible release canidate 1

**Comment by julianpoy** [comment]
Cool. How about you create an issue for this, and mark it as RC1.
I agree generally, but one distinction I want to make clear:
I believe the program can handle up to 30 tracks loaded in the view at a time. I agree that we should restrict the number to 6 concurrent _playing_ songs.

Sound good?
