### ISSUE TITLE
Make Master Channels Sliders affect  in relation to the track current sliders

### ISSUE THREAD

**Issue by torch2424** [julianpoy/HackTech2016#29]
For example, if I have a track on half volume, and I want to simply turn the master volume down a bit,

the child track's volume should move down into relation to the master track, and not simply be the same as master volume

this can be done similar to how I implemented the initVolume for allowing a volume of zero at song playback

**Comment by julianpoy** [comment]
I thought of this, but decided not to do it since it's already pretty functional as it is.
