### ISSUE TITLE
Beat Detection

### ISSUE THREAD

**Issue by torch2424** [julianpoy/HackTech2016#44]
A good article:

http://tech.beatport.com/2014/web-audio/beat-detection-using-web-audio/

Honestly, we can do per track bpm, and use it in relation to playback speed, wouldnt be Too difficult to make them reate, and would be dopeness!

**Comment by torch2424** [comment]
These may also help!

https://github.com/cjcliffe/beatdetektor

Video of beat detektor: https://www.youtube.com/watch?v=OxoFcyKYwr0

https://github.com/jeromeetienne/webaudiox

**Comment by julianpoy** [comment]
Agreed! Both of these issues would be great!

I'm planning on moving the repo over tomorrow and re-setting up the issues.
This repo can stay here and be free for download, and the new repo will be where future development happens :dancer:

**Comment by torch2424** [comment]
Sounds good yo! :)

**Comment by torch2424** [comment]
are you moving it to kondeo or under you still?

**Comment by julianpoy** [comment]
Kondeo, cause we are making this the product thing, right?

**Comment by torch2424** [comment]
Yup yup :)

Kondeo is yo company, if Flyxer is worthy of it, I'd love to :)

**Comment by julianpoy** [comment]
This issue was moved to Kondeo/Flyxer#13
