### ISSUE TITLE
Finish effects

### ISSUE THREAD

**Issue by julianpoy** [julianpoy/HackTech2016#7]
Add the final effects that are provided with the library by default. This expands the functionality of the app as far as possible.

**Comment by torch2424** [comment]
this is in finalEffects

**Comment by torch2424** [comment]
the other effects will be tuna based haha

**Comment by torch2424** [comment]
But we will have that BITCRUSHER YESSSSS!!!!!!!!!!!!!!!!!!!

**Comment by julianpoy** [comment]
WOOT
